#!/usr/bin/env bash

. ./setenv_keystore.sh

# Create etc/ssl dir
if [ ! -d ../etc/ssl ]; then
   mkdir -p ../etc/ssl
fi

#
# Create keystore to store member keys. Password: member
#
keytool -genkey -alias $ALIAS -storetype PKCS12 -keyalg RSA -keysize 2048 \
-keystore $KEYSTORE_FILE \
-storepass $KEYSTORE_PASSWORD \
-dname 'CN=Member, OU=PS, O=Hazelcast, L=PaloAlto, ST=CA, C=US' \
-ext 'SAN=dns:server1.demo.com,dns:'${HOST_NAME}',dns:localhost,ip:127.0.0.1,ip:::1'

echo "    Keystore File: $KEYSTORE_FILE"
echo "Keystore Password: $KEYSTORE_PASSWORD"
