#!/usr/bin/env bash

. ./setenv_keystore.sh

# Create etc/ssl dir
if [ ! -d ../etc/ssl ]; then
   mkdir -p ../etc/ssl
fi

# First, export the member trusted certificate from the member keystore
keytool -export -keystore $KEYSTORE_FILE -alias $ALIAS -file ../etc/ssl/member.cer -storepass $KEYSTORE_PASSWORD

# Import the trusted certificate in a separate keystore
keytool -import -file ../etc/ssl/member.cer -alias $ALIAS \
-keystore $TRUST_KEYSTORE_FILE \
-storepass $KEYSTORE_PASSWORD \
-storetype pkcs12 \
-noprompt

echo "Trust Keystore File: $TRUST_KEYSTORE_FILE"
