#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./$EXECUTABLE [-clean] [-?]"
   echo ""
   echo "   Initializes this cluster. After a build (if required), this script should be executed before running"
   echo "   other scripts to intialize the cluster environment."
   echo ""
   echo "Default: ./$EXECUTABLE"
   echo ""
   exit
fi

# Place the correct version of Hazelcast config file in etc/
cp $APP_DIR/etc/v$HAZELCAST_MAJOR_VERSION_NUMBER/hazelcast.xml $APP_DIR/etc/

echo "Cluster initialized."
