#!/usr/bin/env bash

. ./setenv_keystore.sh

# Create etc/ssl dir
if [ ! -d ../etc/ssl ]; then
   mkdir -p ../etc/ssl
fi

#
# List member keystore
#
keytool -list -storepass $KEYSTORE_PASSWORD -keystore $KEYSTORE_FILE

