#!/usr/bin/env bash

. ./setenv_keystore.sh

# Create etc/ssl dir
if [ ! -d ../etc/ssl ]; then
   mkdir -p ../etc/ssl
fi

#
# List member trust keystore
#
keytool -list -keystore $TRUST_KEYSTORE_FILE -storepass $KEYSTORE_PASSWORD


