#!/usr/bin/env bash

. ./setenv_keystore.sh

# Create etc/ssl dir
if [ ! -d ../etc/ssl ]; then
   mkdir -p ../etc/ssl
fi

# First, export the client trusted certificate from the client keystore
keytool -export -keystore $KEYSTORE_FILE -alias $ALIAS -file ../etc/ssl/client.cer -storepass $KEYSTORE_PASSWORD

# Import the client trusted certificate in a separate trust keystore
keytool -import -file ../etc/ssl/client.cer -alias $ALIAS \
-keystore $TRUST_KEYSTORE_FILE \
-storepass $KEYSTORE_PASSWORD \
-storetype pkcs12 \
-noprompt

echo "Trust Keystore File: $TRUST_KEYSTORE_FILE"
